### ISSUE TITLE
Windows defender regard fastlist as a Trojan

### ISSUE THREAD

**Issue by BakaFT** [MarkTiedemann/fastlist#2] opened 2020-06-23 12:07 UTC
Both fastlist 0.3.1 and 0.2.1 was  blocked when downloaded in MSEDGE by Microsoft Defender SmartScreen.
And Widnows Defender will blocked them too when they are about to start running.

**Comment by MarkTiedemann** [comment] 2020-06-23 14:19
Duplicate of https://github.com/sindresorhus/ps-list/issues/42. Please check that issue for more details.

All versions of fastlist are falsely detected as trojans by some anti-virus software. Here are the reports for v0.3.0:

- `fastlist-0.3.0-x64.exe`: https://www.virustotal.com/gui/file/d1a71f9ac1728082c1b276392725c3e010b98714888579b99152e401abedbf11/detection
- `fastlist-0.3.0-x86.exe`: https://www.virustotal.com/gui/file/017411f3b0b5c0402cc3b2cb87c32c6fc71abd82e5b17ea6108990096c75a65d/detection

I will try to submit v0.3.0 as a false positive at Microsoft Defender, but this may or may not work. I have previously submitted false positive reports to other AV vendors, for example, BitDefender, but have, most of the time, not received any reponse whatsoever.

**Comment by MarkTiedemann** [comment] 2020-06-25 14:42
Windows Defender no longer incorrectly detects fastlist as a trojan.

**Closed as completed by MarkTiedemann** 2020-06-25 14:42 UTC
Labels: antivirus
